version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-orders-challenge-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  app:
    build: .
    container_name: orders-app
    restart: always
    env_file: 
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
